'use client';

import { useEffect, useMemo, useState } from 'react';
import { authFetch } from '@/infrastructure/auth/authFetch';
import { DepotMultiFilter } from './DepotMultiFilter';

type Row = { depotId: string | null; depotName: string; scheduleId: string; sequence: number | null; departureAt: string; licensePlate: string; priority: number; chargingStation: string; location: string };
type End = { name: string; rows: Row[] };
type Route = { routeCode: string; routeName: string; ends: End[] };
const formatTime = (value: string) => new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', hour: '2-digit', minute: '2-digit' }).format(new Date(value));
const locationClass = (location: string) => location === 'Đã sạc' ? 'roster-charged' : location === 'Chưa nhận' ? 'roster-waiting' : location === 'Đang về sạc' ? 'roster-outbound' : location === 'Đang trả xe' ? 'roster-returning' : '';

export function DutyRosterBoard({ query }: { query: string }) {
  const [depotFilter,setDepotFilter]=useState<string[]>([]);
  const [routes, setRoutes] = useState<Route[]>([]); const [role, setRole] = useState(''); const [routeFilter, setRouteFilter] = useState(''); const [stationFilter, setStationFilter] = useState('');
  useEffect(() => { void Promise.all([authFetch('/api/v1/dashboard/roster').then((response) => response.json()), authFetch('/api/v1/me').then((response) => response.ok ? response.json() : null)]).then(([roster, actor]) => { setRoutes(roster.routes ?? []); setRole(actor?.role ?? ''); }); }, []);
  const stations = useMemo(() => [...new Set(routes.flatMap((route) => route.ends.flatMap((end) => end.rows.map((row) => row.chargingStation))).filter(Boolean))].sort(), [routes]);
  const depots=useMemo(()=>Array.from(new Map(routes.flatMap(route=>route.ends.flatMap(end=>end.rows.filter(row=>row.depotId).map(row=>[row.depotId!,{id:row.depotId!,name:row.depotName}] as const)))).values()).sort((a,b)=>a.name.localeCompare(b.name,"vi")),[routes]);
  const filtered = useMemo(() => routes.filter((route) => !routeFilter || route.routeCode === routeFilter).map((route) => ({ ...route, ends: route.ends.map((end) => ({ ...end, rows: end.rows.filter((row) => (!depotFilter.length || (row.depotId !== null && depotFilter.includes(row.depotId))) && (!stationFilter || row.chargingStation === stationFilter) && (!query || `${row.licensePlate} ${route.routeCode} ${row.chargingStation}`.toLowerCase().includes(query.toLowerCase()))) })).filter((end) => end.rows.length) })).filter((route) => route.ends.length), [routes, routeFilter, stationFilter, query, depotFilter]);
  return <section className="roster-panel"><div className="roster-heading"><h2>Xem theo bảng tài</h2><p>Vàng: chưa nhận · Xanh lá: đã sạc · Xanh dương: đang về sạc · Cam: đang trả xe.</p>{role === 'admin' && <div className="roster-filters"><label>Tuyến<select value={routeFilter} onChange={(event) => setRouteFilter(event.target.value)}><option value="">Tất cả tuyến</option>{routes.map((route) => <option key={route.routeCode} value={route.routeCode}>Tuyến {route.routeCode}</option>)}</select></label><label>Trạm sạc<select value={stationFilter} onChange={(event) => setStationFilter(event.target.value)}><option value="">Tất cả trạm</option>{stations.map((station) => <option key={station} value={station}>{station}</option>)}</select></label></div>}</div><DepotMultiFilter options={depots} selected={depotFilter} onChange={setDepotFilter}/><div className="roster-scroll">{filtered.map((route) => <section className="route-table" key={route.routeCode}><h3>Tuyến {route.routeCode}</h3>{route.ends.map((end, endIndex) => <div key={`${end.name}-${endIndex}`}><h4>{end.name}</h4><table><thead><tr><th>STT</th><th>Giờ XB</th><th>BSX</th><th>Ưu tiên</th><th>Trạm sạc</th><th>Vị trí hiện tại</th></tr></thead><tbody>{end.rows.map((row, index) => <tr key={row.scheduleId} className={locationClass(row.location)}><td>{row.sequence ?? index + 1}</td><td>{formatTime(row.departureAt)}</td><td>{row.licensePlate}</td><td>Ưu tiên {row.priority}</td><td>{row.chargingStation}</td><td>{row.location}</td></tr>)}</tbody></table></div>)}</section>)}{!filtered.length && <p>Không có xe phù hợp với bộ lọc.</p>}</div></section>;
}
