'use client';
import { useEffect, useMemo, useState } from 'react';
import type { YardLocation } from '@/components/yard-map/YardMapCanvas';
import { StreetOperationsMap } from '@/features/map/StreetOperationsMap';
import { TaskKanbanBoard } from '@/features/dispatch-tasks/TaskKanbanBoard';
import { QrReceiveFlow } from '@/features/dispatch-tasks/QrReceiveFlow';
import { useDispatchTasksRealtime } from '@/features/dispatch-tasks/useDispatchTasksRealtime';
import type { UserRole } from '@/domain/task/taskStateMachine';
import { ThemeToggle } from '@/components/theme/ThemeToggle';
import { LogoutButton } from '@/components/auth/LogoutButton';
import { authFetch } from '@/infrastructure/auth/authFetch';
import './dashboard.css';
type Actor = { userId: string; role: UserRole; fullName: string };
const viTime = (value: string | null | undefined) => value ? new Intl.DateTimeFormat('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh', day: '2-digit', month: '2-digit', year: 'numeric', hour: '2-digit', minute: '2-digit', hour12: false }).format(new Date(value)) : '—';
const taskStatusLabel: Record<string, string> = { chua_sac: 'Chưa nhận', nhan_xe_dau_ben: 'Đã nhận xe', giao_tram_sac: 'Giao trạm sạc', nhan_tram_sac: 'Trả xe', giao_dau_ben: 'Đã trả xe', hoan_thanh: 'Hoàn thành', qua_han: 'Quá hạn' };
export default function DashboardPage() {
  const [depots, setDepots] = useState<YardLocation[]>([]); const [stations, setStations] = useState<YardLocation[]>([]); const [staff, setStaff] = useState<any[]>([]); const [station, setStation] = useState<string | null>(null); const [actor, setActor] = useState<Actor | null>(null); const [q, setQ] = useState(''); const [announcements,setAnnouncements]=useState<any[]>([]); const [canManageAnnouncements,setCanManageAnnouncements]=useState(false); const [violationAlerts,setViolationAlerts]=useState<any[]>([]); const [canAcknowledgeViolations,setCanAcknowledgeViolations]=useState(false); const { tasks, loading, loadError, scopeNotice } = useDispatchTasksRealtime();
  useEffect(() => { const loadMap = async () => { try { const response = await authFetch('/api/v1/map/yard'); if (!response.ok) return; const data = await response.json(); setDepots(data.depots ?? []); setStations(data.stations ?? []); setStaff(data.staffLocations ?? []); } catch { /* network reconnect will retry after 15 seconds */ } }; const loadAnnouncements=()=>authFetch('/api/v1/announcements').then(r=>r.ok?r.json():null).then(d=>{if(d){setAnnouncements(d.announcements??[]);setCanManageAnnouncements(Boolean(d.canManage))}}).catch(()=>undefined); const loadViolations=()=>authFetch('/api/v1/violations/active').then(r=>r.ok?r.json():null).then(d=>{if(d){setViolationAlerts(d.alerts??[]);setCanAcknowledgeViolations(Boolean(d.canAcknowledge))}}).catch(()=>undefined); void loadMap();void loadAnnouncements();void loadViolations(); const timer = window.setInterval(()=>void loadMap(), 15000); const announceTimer=window.setInterval(()=>void loadAnnouncements(),60000); const violationTimer=window.setInterval(()=>void loadViolations(),30000); authFetch('/api/v1/me').then((response) => response.ok ? response.json() : null).then(setActor).catch(()=>setActor(null)); return () => {window.clearInterval(timer);window.clearInterval(announceTimer);window.clearInterval(violationTimer)}; }, []);
  const addAnnouncement=async()=>{const message=window.prompt('Nội dung thông báo cho toàn bộ nhân viên:')?.trim();if(!message)return;const until=window.prompt('Thời điểm tự tắt (YYYY-MM-DDTHH:mm), để trống nếu tự tắt thủ công:')?.trim();const response=await authFetch('/api/v1/announcements',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message,visibleUntil:until||null})});const data=await response.json();if(!response.ok){window.alert(data.error?.message??'Không thể đăng thông báo.');return;}setAnnouncements(x=>[data.announcement,...x]);};
  const turnOffAnnouncement=async(id:string)=>{await authFetch('/api/v1/announcements',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});setAnnouncements(x=>x.filter(a=>a.id!==id));};
  const acknowledgeViolation=async(id:string)=>{const response=await authFetch('/api/v1/violations/active',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id})});const data=await response.json();if(!response.ok){window.alert(data.error?.message??'Không thể tắt cảnh báo vi phạm.');return;}setViolationAlerts(items=>items.filter(item=>item.id!==id));};
  const cards = useMemo<any[]>(() => tasks.map((task: any) => ({ id: task.id, loaiTask: task.task_type, trangThai: task.status, eta: task.eta_at, priorityLctAt: task.priority_lct_at, vehicleId: task.vehicle_id, vehiclePlate: task.vehicles?.license_plate, routeCode: task.daily_vehicle_schedules?.plan_route_ends?.route_code, departureAt: task.daily_vehicle_schedules?.earliest_departure_at, sequence: task.daily_vehicle_schedules?.roster_sequence, assignedUserId: task.assigned_profile_id, assignedName: task.assigned_profile?.full_name, fromLocationId: task.from_depot_id, toLocationId: task.to_station_id })), [tasks]);
  const shownDepots = station ? depots.filter((item) => cards.some((task) => task.toLocationId === station && task.fromLocationId === item.id)) : depots; const shownStations = station ? stations.filter((item) => item.id === station) : stations; const scopedStaff = staff.filter((item) => !station || item.stationId === station); const filtered = cards.filter((task) => (!station || task.toLocationId === station) && (!q || `${task.vehiclePlate} ${task.routeCode}`.toLowerCase().includes(q.toLowerCase())));
  const downloadLct=()=>{const rows=[['Biển số','Tuyến','STT bảng tài','Giờ xuất bến (giờ VN)','LCT bắt đầu điều chuyển (giờ VN)','Trạng thái'],...cards.filter(item=>item.loaiTask==='di_chuyen').map(item=>[item.vehiclePlate??'',item.routeCode??'',String(item.sequence??''),viTime(item.departureAt),viTime(item.priorityLctAt),taskStatusLabel[item.trangThai]??item.trangThai])];const csv='\uFEFF'+rows.map(row=>row.map(value=>`"${String(value).replaceAll('"','""')}"`).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`LCT-${new Date().toISOString().slice(0,10)}.csv`;link.click();URL.revokeObjectURL(url);};
  const archiveAllTasks = async () => {
    const confirmation = window.prompt('Nhập XOA-TOAN-BO-TASK để xác nhận ẩn toàn bộ task của ngày hiện tại. Lịch sử, ảnh và GPS không bị xoá.');
    if (confirmation !== 'XOA-TOAN-BO-TASK') return;
    const response = await authFetch('/api/v1/admin/dispatch-reset', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirmation }) });
    const data = await response.json();
    if (!response.ok) { window.alert(data.error?.message ?? 'Không thể xoá task.'); return; }
    window.alert(data.message); window.location.reload();
  };
  return <main className="dispatch-dashboard"><header className="dispatch-header"><div><h1 className="dispatch-title">Điều phối trạm sạc</h1><p className="dispatch-subtitle">Xin chào, {actor?.fullName ?? 'bạn'}</p></div><div className="header-actions">{actor?.role==='admin'&&<><button className="announcement-add" onClick={downloadLct}>Tải LCT</button><button className="announcement-add" onClick={archiveAllTasks}>Xóa task ngày</button></>}{canManageAnnouncements&&<button className="announcement-add" onClick={addAnnouncement}>+ Thông báo</button>}<QrReceiveFlow actor={actor}/><ThemeToggle/><LogoutButton/></div></header>{violationAlerts.length>0&&<section className="violation-bar">{violationAlerts.map(alert=>{const item=alert.violation_cases;return <article key={alert.id}><span><strong>⚠ Cảnh báo vi phạm{item?.recurrence_count>1?` · tái phạm lần ${item.recurrence_count}/30 ngày`:''}</strong><br/>{item?.profiles?.full_name??'—'} · MSNV {item?.profiles?.employee_code??'—'} · Xe {item?.vehicles?.license_plate??'—'} · {item?.charging_stations?.name??'—'} · {item?.message??'—'}</span>{canAcknowledgeViolations&&<button onClick={()=>acknowledgeViolation(alert.id)}>Tắt</button>}</article>})}</section>}{announcements.length>0&&<section className="announcement-bar">{announcements.map(a=><article key={a.id}><span>{a.message}</span>{canManageAnnouncements&&<button onClick={()=>turnOffAnnouncement(a.id)}>Tắt</button>}</article>)}</section>}<div className="dashboard-search"><input value={q} onChange={(event) => setQ(event.target.value)} placeholder="Tìm biển số hoặc mã tuyến…"/></div><div className="dashboard-grid"><section className="map-panel"><div className="panel-heading"><h2>Bản đồ vận hành</h2><select value={station ?? ''} onChange={(event) => setStation(event.target.value || null)}><option value="">Tất cả trạm</option>{stations.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></div><div className="map-canvas"><StreetOperationsMap depots={shownDepots} stations={shownStations} staffLocations={scopedStaff}/></div></section><section className="tasks-panel"><h2>Task di chuyển</h2><p>{loading ? 'Đang tải…' : `${filtered.filter((item) => item.trangThai !== 'hoan_thanh').length} xe chưa hoàn thành`}</p>{scopeNotice && <p className="dashboard-error">{scopeNotice}</p>}{loadError && <p className="dashboard-error">{loadError}</p>}<TaskKanbanBoard tasks={filtered} scope="di_chuyen" actor={actor}/></section></div></main>;
}
