'use client';

import { FormEvent, useEffect, useState } from 'react';
import { authFetch } from '@/infrastructure/auth/authFetch';

type ManualKind = 'depot' | 'station' | 'vehicle' | 'pa';
type Card = { title: string; endpoint: string; columns: string; exportPath?: string; templatePath?: string; roster?: boolean; pa?: boolean; manualKind?: ManualKind };
type PendingVehicle = { licensePlate: string; vehicleTypeCode: string };
type Options = { vehicleTypes: string[]; depots: string[]; stations: string[] };

const cards: Card[] = [
  { title: '1. Import bãi đậu', endpoint: '/api/v1/import/depots', columns: 'Tên bãi | X | Y | Địa chỉ', templatePath: '/api/v1/import/depots/template', exportPath: '/api/v1/export/depots', manualKind: 'depot' },
  { title: '2. Import trạm sạc', endpoint: '/api/v1/import/stations', columns: 'Tên trạm | X | Y | Công suất', templatePath: '/api/v1/import/stations/template', exportPath: '/api/v1/export/stations', manualKind: 'station' },
  { title: '3. Import danh mục xe', endpoint: '/api/v1/import/vehicles', columns: 'Biển số | Loại xe', templatePath: '/api/v1/import/vehicles/template', exportPath: '/api/v1/export/vehicles', manualKind: 'vehicle' },
  { title: '4. Import PA đậu đêm cố định', endpoint: '/api/v1/import/routes', columns: 'Mã tuyến | Tên tuyến | Đầu bến | Bãi đậu đêm | Trạm sạc | Số xe PA | Thời gian huy động (phút) | Buffer (phút)', templatePath: '/api/v1/import/routes/template', exportPath: '/api/v1/export/overnight-plan', pa: true, manualKind: 'pa' },
  { title: '5. Import bảng tài tiêu chuẩn', endpoint: '/api/v1/import/duty-roster', columns: 'Giữ nguyên form chuẩn: Tài/STT | GIỜ XB | BSX tại từng đầu bến.', templatePath: '/api/v1/import/duty-roster/template', roster: true },
];

async function responseBody(response: Response) { const raw = await response.text(); try { return JSON.parse(raw); } catch { return { error: { message: `Máy chủ trả về HTTP ${response.status}, nhưng không gửi dữ liệu lỗi hợp lệ.`, details: raw ? [raw.slice(0, 500)] : [] } }; } }
async function downloadApi(path: string) { const response = await authFetch(path); if (!response.ok) throw new Error((await response.json()).error?.message ?? 'Không thể tải dữ liệu.'); const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = response.headers.get('content-disposition')?.match(/filename="?([^";]+)/)?.[1] ?? 'du-lieu.xlsx'; anchor.click(); URL.revokeObjectURL(url); }

function UploadCard({ card, onManual }: { card: Card; onManual: (kind: ManualKind) => void }) {
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date());
  const [file, setFile] = useState<File | null>(null); const [effectiveFrom, setEffectiveFrom] = useState(today); const [serviceDate, setServiceDate] = useState(today); const [result, setResult] = useState(''); const [details, setDetails] = useState<string[]>([]); const [failed, setFailed] = useState(false); const [loading, setLoading] = useState(false); const [pendingVehicles, setPendingVehicles] = useState<PendingVehicle[]>([]); const [vehicleTypes, setVehicleTypes] = useState<string[]>([]);
  const submit = async (event: FormEvent) => {
    event.preventDefault(); if (!file) return;
    if (pendingVehicles.some((vehicle) => !vehicle.vehicleTypeCode)) { setFailed(true); setResult('Hãy chọn loại xe cho toàn bộ biển số mới trước khi xác nhận import.'); return; }
    setLoading(true); setResult(''); setDetails([]); setFailed(false); const body = new FormData(); body.set('file', file); if (card.pa) body.set('effectiveFrom', effectiveFrom); if (card.roster) body.set('serviceDate', serviceDate); if (pendingVehicles.length) body.set('newVehicles', JSON.stringify(pendingVehicles));
    try { const response = await authFetch(card.endpoint, { method: 'POST', body }); const data = await responseBody(response); if (data.needsVehicleConfirmation) { const plates = Array.isArray(data.missingVehicles) ? data.missingVehicles.map(String) : []; setPendingVehicles(plates.map((licensePlate: string) => ({ licensePlate, vehicleTypeCode: '' }))); setVehicleTypes(Array.isArray(data.vehicleTypes) ? data.vehicleTypes.map(String) : []); setResult(data.message ?? `Có ${plates.length} xe chưa có trong danh mục.`); setDetails(['Chọn loại xe cho từng biển số phía dưới, sau đó bấm “Xác nhận thêm xe và import”.']); return; } setPendingVehicles([]); setVehicleTypes([]); setFailed(!response.ok); setResult(response.ok ? data.message ?? 'Đã import thành công.' : data.error?.message ?? data.message ?? `Import thất bại (HTTP ${response.status}).`); setDetails(Array.isArray(data.error?.details) ? data.error.details.map(String) : []); } catch (caught) { setFailed(true); setResult(`Không thể kết nối máy chủ: ${caught instanceof Error ? caught.message : 'lỗi không xác định.'}`); } finally { setLoading(false); }
  };
  return <article className="import-card"><div><h2>{card.title}</h2><p>Cột hệ thống đọc: <b>{card.columns}</b></p>{card.pa && <p>PA là cấu hình cố định. Thêm thủ công sẽ tạo phiên bản mới nhưng giữ nguyên các dòng đang có.</p>}{card.roster && <p>Chọn <b>ngày vận doanh</b>. Chỉ tuyến đang nhập được cập nhật, các tuyến khác được giữ nguyên.</p>}</div><div className="import-actions">{card.manualKind && <button type="button" className="manual-add" onClick={() => onManual(card.manualKind!)}>+ Thêm thủ công</button>}{card.templatePath && <button type="button" onClick={() => window.open(card.templatePath, '_self')}>Tải mẫu Excel</button>}{card.exportPath && <button type="button" onClick={() => downloadApi(card.exportPath!).catch((error: Error) => { setFailed(true); setResult(error.message); })}>Tải dữ liệu hiện tại</button>}</div><form onSubmit={submit}>{card.pa && <label>Hiệu lực từ <input type="date" value={effectiveFrom} onChange={(event) => setEffectiveFrom(event.target.value)} required /></label>}{card.roster && <label>Ngày vận doanh <input type="date" value={serviceDate} onChange={(event) => setServiceDate(event.target.value)} required /></label>}<input type="file" accept=".xlsx,.xls" onChange={(event) => { setFile(event.target.files?.[0] ?? null); setPendingVehicles([]); }} /><button className="import-submit" disabled={!file || loading}>{loading ? 'Đang tải lên…' : pendingVehicles.length ? 'Xác nhận thêm xe và import' : 'Đối chiếu và import'}</button></form>{pendingVehicles.length > 0 && <section className="new-vehicle-confirm"><h3>Xác nhận xe mới ({pendingVehicles.length})</h3>{pendingVehicles.map((vehicle, index) => <label key={vehicle.licensePlate}><b>{vehicle.licensePlate}</b><select value={vehicle.vehicleTypeCode} onChange={(event) => setPendingVehicles((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, vehicleTypeCode: event.target.value } : item))}><option value="">Chọn loại xe</option>{vehicleTypes.map((type) => <option key={type}>{type}</option>)}</select></label>)}</section>}{result && <div className={failed ? 'import-result import-result-error' : 'import-result'}><p>{result}</p>{details.length > 0 && <ul>{details.slice(0, 50).map((item, index) => <li key={index}>{item}</li>)}</ul>}</div>}</article>;
}

function ManualModal({ kind, onClose }: { kind: ManualKind; onClose: (message?: string) => void }) {
  const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Ho_Chi_Minh' }).format(new Date()); const [options, setOptions] = useState<Options>({ vehicleTypes: [], depots: [], stations: [] }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  useEffect(() => { void authFetch('/api/v1/manual-data').then((response) => response.json()).then((data) => setOptions(data)); }, []);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setLoading(true); setError(''); const values = Object.fromEntries(new FormData(event.currentTarget)); try { const response = await authFetch('/api/v1/manual-data', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ kind, ...values }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error?.message ?? 'Không thể lưu dữ liệu.'); onClose(data.message); } catch (caught) { setError(caught instanceof Error ? caught.message : 'Không thể lưu dữ liệu.'); } finally { setLoading(false); } };
  const title = { depot: 'bãi đậu', station: 'trạm sạc', vehicle: 'xe', pa: 'dòng PA đậu đêm' }[kind];
  return <div className="manual-modal" role="dialog" aria-modal="true" aria-labelledby="manual-title"><form onSubmit={submit}><header><div><h2 id="manual-title">Thêm thủ công {title}</h2><p>Hệ thống vẫn áp dụng kiểm tra trùng và ràng buộc như import Excel.</p></div><button type="button" onClick={() => onClose()} aria-label="Đóng">×</button></header>{(kind === 'depot' || kind === 'station') && <><label>Tên <input name="name" required autoFocus /></label><div className="manual-grid"><label>X (vĩ độ) <input name="x" type="number" step="any" required /></label><label>Y (kinh độ) <input name="y" type="number" step="any" required /></label></div>{kind === 'depot' && <label>Địa chỉ <input name="address" /></label>}</>}{kind === 'vehicle' && <><label>Biển số <input name="licensePlate" required autoFocus /></label><label>Loại xe <select name="vehicleTypeCode" required><option value="">Chọn loại xe</option>{options.vehicleTypes.map((value) => <option key={value}>{value}</option>)}</select></label></>}{kind === 'pa' && <><div className="manual-grid"><label>Mã tuyến <input name="routeCode" required /></label><label>Tên tuyến <input name="routeName" /></label></div><label>Đầu bến <input name="routeEndName" required /></label><div className="manual-grid"><label>Bãi đậu đêm <select name="depotName" required><option value="">Chọn bãi</option>{options.depots.map((value) => <option key={value}>{value}</option>)}</select></label><label>Trạm sạc <select name="stationName" required><option value="">Chọn trạm</option>{options.stations.map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="manual-grid manual-grid-3"><label>Số xe PA <input name="plannedVehicleCount" type="number" min="0" required /></label><label>Huy động (phút) <input name="mobilizationMinutes" type="number" min="0" required /></label><label>Buffer (phút) <input name="bufferMinutes" type="number" min="0" defaultValue="10" required /></label></div><label>Hiệu lực từ <input name="effectiveFrom" type="date" defaultValue={today} required /></label><label>Ghi chú <input name="note" /></label><p className="manual-warning">Lưu sẽ kích hoạt phiên bản PA mới và giữ nguyên các dòng PA khác.</p></>}{error && <p className="manual-error">{error}</p>}<footer><button type="button" onClick={() => onClose()}>Hủy</button><button className="primary" disabled={loading}>{loading ? 'Đang lưu…' : 'Lưu dữ liệu'}</button></footer></form></div>;
}

export default function ImportDemoPage() { const [manualKind, setManualKind] = useState<ManualKind | null>(null); const [notice, setNotice] = useState(''); return <main className="import-page"><header><h1>Nhập / xuất dữ liệu</h1><p>Import hàng loạt bằng Excel hoặc thêm trực tiếp từng bản ghi.</p></header>{notice && <div className="import-page-notice">{notice}</div>}{cards.map((card) => <UploadCard key={card.endpoint} card={card} onManual={setManualKind} />)}{manualKind && <ManualModal kind={manualKind} onClose={(message) => { setManualKind(null); if (message) setNotice(message); }} />}</main>; }
